version: '3'
services:
  application:
    image: waldemarnt/cakephp
    volumes:
      - ./:/var/www/cake-php
    tty: true

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  php:
    image: bitnami/php-fpm
    expose:
      - 9000
    volumes_from:
      - application
    links:
      - db
  nginx:
    image: waldemarnt/cakephp-nginx
    ports:
      - 8080:80
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
