version: "3"
services:
  php:
    image: azukiapp/php-fpm
    container_name: cakephp-fpm
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/public
    links:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker