version: "3"
services:
  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: welton/nodejs
    container_name: nodejs
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    volumes:
      - ./:/var/www
      - /var/www/node_modules # Remove this if you have pure JS dependencies
        
  mongo:
    image: mongo
    ports:
      - "27017:27017"