version: "3"
services:
  php:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: welton/php-5.6-apache
    container_name: php-5.6-apache
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker